# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_test1DialogBase(object):
    def setupUi(self, test1DialogBase):
        test1DialogBase.setObjectName("test1DialogBase")
        test1DialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(test1DialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.pbColor = QtWidgets.QPushButton(test1DialogBase)
        self.pbColor.setGeometry(QtCore.QRect(110, 160, 181, 71))
        self.pbColor.setObjectName("pbColor")
        self.comboBox = QtWidgets.QComboBox(test1DialogBase)
        self.comboBox.setGeometry(QtCore.QRect(160, 20, 79, 27))
        self.comboBox.setEditable(True)
        self.comboBox.setCurrentText("")
        self.comboBox.setMaxVisibleItems(4)
        self.comboBox.setObjectName("comboBox")
        self.button2 = QtWidgets.QPushButton(test1DialogBase)
        self.button2.setGeometry(QtCore.QRect(150, 90, 87, 27))
        self.button2.setObjectName("button2")

        self.retranslateUi(test1DialogBase)
        self.comboBox.setCurrentIndex(-1)
        self.button_box.accepted.connect(test1DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(test1DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(test1DialogBase)

    def retranslateUi(self, test1DialogBase):
        _translate = QtCore.QCoreApplication.translate
        test1DialogBase.setWindowTitle(_translate("test1DialogBase", "test1"))
        self.pbColor.setText(_translate("test1DialogBase", "Color !"))
        self.button2.setText(_translate("test1DialogBase", "Hii"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    test1DialogBase = QtWidgets.QDialog()
    ui = Ui_test1DialogBase()
    ui.setupUi(test1DialogBase)
    test1DialogBase.show()
    sys.exit(app.exec_())
