# -*- coding: utf-8 -*-
"""
/***************************************************************************
 mover2
                                 A QGIS plugin
 mover2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-10
        copyright            : (C) 2024 by sk
        email                : shreyas.08kat@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load mover2 class from file mover2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mover2 import mover2
    return mover2(iface)
