# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LGanalysis
                                 A QGIS plugin
 Heatmap analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-05-20
        git sha              : $Format:%H$
        copyright            : (C) 2024 by sk
        email                : shreyas.08kat@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .LGanalysis_dialog import LGanalysisDialog
import os.path
import os
from .psql import *
from .LGanalysis_dialog import HeatMapToggle

import psycopg2
import os
import qgis.utils
import qgis

from PyQt5.QtGui import QColor
from PyQt5 import QtCore
from PyQt5.QtCore import QPointF, Qt
from qgis.PyQt import uic, QtWidgets

from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsSymbol,
    QgsRendererRange,
    QgsGraduatedSymbolRenderer,
    QgsFeature,
    QgsGeometry,
    QgsSingleSymbolRenderer,
    QgsFillSymbol,
    QgsExpression,
    QgsPalLayerSettings,
    QgsVectorLayerSimpleLabeling,
    QgsTextFormat,
    QgsTextBufferSettings,
    QgsPointXY,
    QgsAnnotation,
    QgsCoordinateReferenceSystem,
    QgsTextAnnotation,
    QgsRuleBasedRenderer,
    QgsGradientColorRamp
)
from qgis.gui import QgsMapCanvasAnnotationItem
from qgis.gui import QgsMapToolEmitPoint
from PyQt5.QtGui import QColor, QTextDocument, QFont
from PyQt5.QtCore import QSizeF, QPointF
from PyQt5.QtWidgets import QDialog, QVBoxLayout, QCheckBox, QDockWidget, QWidget, QFormLayout

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

class LGanalysis:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'LGanalysis_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&LGanalysis')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('LGanalysis', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/LGanalysis/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'LGanalysis'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&LGanalysis'),
                action)
            self.iface.removeToolBarIcon(action)


    def initiate(self):
        if self.dlg.lineEdit_farmplots.text():
            self.farmplots_in = self.dlg.lineEdit_farmplots.text()
        else:
            self.farmplots_in = "farmplots"
            
        if self.dlg.lineEdit_survey_georef.text():
            self.survey_georef_in = self.dlg.lineEdit_survey_georef.text()
        else:
            self.survey_georef_in = "survey_georeferenced"
            
        if self.dlg.lineEdit_jitter_spline.text():
            self.jitter_spline_in = self.dlg.lineEdit_jitter_spline.text()
        else:
            self.jitter_spline_in = "jitter_spline_output_regularised_03"
            
        if self.dlg.lineEdit_jitter_polygon.text():
            self.jitter_polygon_in = self.dlg.lineEdit_jitter_polygon.text()
        else:
            self.jitter_polygon_in = "jitter_polygons_regularised_03"
            
        self.heatmap_toggle = None
        
        if self.dlg.lineEdit_host.text():
            self.host = self.dlg.lineEdit_host.text()
        else:
            self.host = "localhost"
        
        if self.dlg.lineEdit_user.text():
            self.user = self.dlg.lineEdit_user.text()
        else:
            self.user = "postgres"
            
        if self.dlg.lineEdit_port.text():
            self.port = self.dlg.lineEdit_port.text()
        else:
            self.port = "5432"
            
        if self.dlg.lineEdit_password.text():
            self.password = self.dlg.lineEdit_password.text()
        else:
            self.password = "postgres"
            
        if self.dlg.lineEdit_database.text():
            self.database = self.dlg.lineEdit_database.text()
        else:
            self.database = "dolr"
    
    def load_maps(self):
        maps = [self.farmplots_in, self.survey_georef_in, self.jitter_spline_in, self.jitter_polygon_in]
        village = self.dlg.village_in.text()
        map = maps[0]
        layer = QgsVectorLayer(
                        f"dbname='{self.database}' host={self.host} port={self.port} user='{self.user}' password='{self.password}' sslmode=disable key='unique_id' srid=32643 type=Polygon table=\"{village}\".\"{map}\" (geom)",
                        f"{map}",
                        "postgres"
                    )
        if not layer.isValid():
            print("Layer failed to load!")
        else :
            
            symbol = QgsFillSymbol.createSimple({'color': 'green'})
            symbol.setOpacity(0.3)
            renderer = QgsSingleSymbolRenderer(symbol)
            layer.setRenderer(renderer)
            layer.triggerRepaint()
            QgsProject.instance().addMapLayer(layer)
            
        map = maps[1]
        layer = QgsVectorLayer(
                        f"dbname='{self.database}' host={self.host} port={self.port} user='{self.user}' password='{self.password}' sslmode=disable key='unique_id' srid=32643 type=Polygon table=\"{village}\".\"{map}\" (geom)",
                        f"{map}",
                        "postgres"
                    )
        if not layer.isValid():
            print("Layer failed to load!")
        else :
            symbol = QgsFillSymbol.createSimple({'color': QColor(0,0,0,0), 'outline_color': QColor('#3579b1'), 'outline_width': '1'})
            renderer = QgsSingleSymbolRenderer(symbol)
            layer.setRenderer(renderer)
            layer.triggerRepaint()
            QgsProject.instance().addMapLayer(layer)
            
        map = maps[2]
        layer = QgsVectorLayer(
                        f"dbname='{self.database}' host={self.host} port={self.port} user='{self.user}' password='{self.password}' sslmode=disable key='unique_id' srid=32643 type=Polygon table=\"{village}\".\"{map}\" (geom)",
                        f"{map}",
                        "postgres"
                    )
        if not layer.isValid():
            print("Layer failed to load!")
        else :
            symbol = QgsFillSymbol.createSimple({'color': QColor(0,0,0,0), 'outline_color': QColor('#e41a1c'), 'outline_width': '1'})
            renderer = QgsSingleSymbolRenderer(symbol)
            layer.setRenderer(renderer)
            layer.triggerRepaint()
            QgsProject.instance().addMapLayer(layer)
        
        map = maps[3]
        layer = QgsVectorLayer(
                        f"dbname='{self.database}' host={self.host} port={self.port} user='{self.user}' password='{self.password}' sslmode=disable key='unique_id' srid=32643 type=Polygon table=\"{village}\".\"{map}\" (geom)",
                        f"{map}",
                        "postgres"
                    )
        if not layer.isValid():
            print("Layer failed to load!")
        else :
            symbol = QgsFillSymbol.createSimple({'color': QColor(0,0,0,0), 'outline_color': QColor('#000000'), 'outline_width': '1'})
            renderer = QgsSingleSymbolRenderer(symbol)
            layer.setRenderer(renderer)
            layer.triggerRepaint()
            QgsProject.instance().addMapLayer(layer)
        
        
    def generate_heatmap(self, attribute, custom_field = None, custom_ranges = None):
        print("generating heatmap")
        layer = QgsProject.instance().mapLayersByName(self.jitter_spline_in)[0]
        field = attribute
        if field == "farm_rating":
            colors = [(0.0, QColor('#d7191c')), (0.8, QColor('#ffffc0')), (0.9, QColor('#1a9641')), (1.0, QColor('blue'))]
        
        elif field == "corrected_area_diff":
            colors = [(-100000, QColor('#ca0020')), (-0.05, QColor('#ec846e')), (-0.03, QColor('#f6d6c8')), (-0.01, QColor('#d3d3d3')), (0.01, QColor('#cfe3ed')), (0.03, QColor('#76b4d5')), (0.05, QColor('#0571b0')), (100000, QColor('blue'))]
        
        elif field == 'excess_area':
            colors = [(0.0, QColor('#d3d3d3')), (0.01, QColor('#cfe3ed')), (0.03, QColor('#76b4d5')), (0.05, QColor('#0571b0')), (10000000, QColor('blue'))]
        
        elif field == "custom":
            field = custom_field
            n = len(custom_ranges)
            print("n is ", n, custom_field, custom_ranges)
            # cmap = mcolors.LinearSegmentedColormap.from_list("mycmap", ['#d7191c', '#1a9641'])
            colorRamp = QgsGradientColorRamp.create({'color1': '#d7191c', 'color2': '#1a9641', 'stops': '0.5;#ffffbf'})
            colors = [colorRamp.color(i/(n-1)).name() for i in range(n)]
            colors = colors[::-1]
            print(colors)
            fin_ranges = []
            for i in range(n):
                symbol = QgsSymbol.defaultSymbol(layer.geometryType())
                symbol.setColor(QColor(colors[i]))
                rng = QgsRendererRange(custom_ranges[i][0], custom_ranges[i][1], symbol, f"{custom_ranges[i][0]} - {custom_ranges[i][1]}")
                fin_ranges.append(rng)
            
            renderer = QgsGraduatedSymbolRenderer(field, fin_ranges)
            layer.setRenderer(renderer)
            layer.triggerRepaint()
            self.iface.layerTreeView().refreshLayerSymbology(layer.id())
            return
        
        ranges = []
        for i in range(len(colors) - 1):
            symbol = QgsSymbol.defaultSymbol(layer.geometryType())
            symbol.setColor(colors[i][1])
            rng = QgsRendererRange(colors[i][0], colors[i+1][0], symbol, f"{100*colors[i][0]} - {100*colors[i+1][0]}")
            ranges.append(rng)

        renderer = QgsGraduatedSymbolRenderer(field, ranges)
        layer.setRenderer(renderer)

        layer.triggerRepaint()
        self.iface.layerTreeView().refreshLayerSymbology(layer.id())
        
    def on_layers_removed(self, layers):
        if len(QgsProject.instance().mapLayers()) == 0:
            if self.heatmap_toggle:
                self.iface.removeDockWidget(self.heatmap_toggle)
                self.heatmap_toggle.deleteLater()
                self.heatmap_toggle = None
    
    def remove_heatmap(self):
        print("removing heatmap")
        layer = QgsProject.instance().mapLayersByName(self.jitter_spline_in)[0]
        symbol = QgsFillSymbol.createSimple({'color': QColor(0,0,0,0), 'outline_color': QColor('#e41a1c'), 'outline_width': '1'})
        layer.setRenderer(QgsSingleSymbolRenderer(symbol))
        layer.triggerRepaint()
        self.iface.layerTreeView().refreshLayerSymbology(layer.id())
    
    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = LGanalysisDialog(self.iface)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            QgsProject.instance().layersRemoved.connect(self.on_layers_removed)
            self.initiate()
            self.load_maps()
            if self.heatmap_toggle is None:    
                self.heatmap_toggle = HeatMapToggle(self.iface.mainWindow(), self)
                self.iface.addDockWidget(Qt.RightDockWidgetArea, self.heatmap_toggle)
                
