# -*- coding: utf-8 -*-
"""
/***************************************************************************
 heatmap
                                 A QGIS plugin
 generates heatmap
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-15
        copyright            : (C) 2024 by sk
        email                : shreyas.08kat@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load heatmap class from file heatmap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .heatmap import heatmap
    return heatmap(iface)
